- name: install and start nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install mginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    
    
 
# In Ansible, become: yes  means run the task with admin (root) permission
