- name: varibles from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the course info 
    ansible.builtin.debug:
      msg: "The variables are coming from varible file: course.yaml"
    ansible.builtin.debug:
      msg: "The course name is: {{COURSE}} and duration is: {{DURATION}} and Trainer is: {{TRAINER}}"