- name: varibless from prompt
  hosts: local
  connection: local 
  vars_prompt:
    - name: username
      prompt: please enter the usename?
      private: false
  tasks:
    - name: display the entered username
      ansible.builtin.debug:
        msg: "the entered name is: {{ username }}"
