- name: conditions
  hosts: local
  connection: local
  vars:
    number: 4
  tasks:
  - name: checking the number is less than 10 or not
    ansible.builtin.debug:
      msg: "the entered number is lessthan 10"
    when: number < 10