- name: Install pacakges
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - mongod


# In Ansible, state: latest means make sure the package is installed and updated to the newest version.