- name: functions
  hosts: local
  connection: local
  # vars:
  #   name: "Rockey Bai"
  tasks:
  - name: default varible
    ansible.builtin.debug:
      msg: "Hello my name is {{ name | default ('prakash') }}"


# "The default function prints the defined variable if it exists; otherwise, it prints the default variable that is defined."