- name: loop
  hosts: local
  tasks:
    - name: print names in loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
      - abhiskek
      - karthik
      - lokesh
      - pavan
 

 