- name: setting nginx
  hosts: frontend
  tasks:
    - name: getting varibles from inventory files
      vars:
        SUB: "ENGLISH"
      ansible.builtin.debug:
        msg: "the trainer teaches: {{ SUB }} subject "

 

 