- name: grep for root 
  hosts: local
  connection: local
  tasks:
  - name: grep for root 
    #ansible.builtin.command:  cat /etc/passwd | grep root
    ansible.builtin.shell:  cat /etc/passwd | grep root
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"







# the register keyword is used to capture the output (result) of a task and store it in a variable

# shell vs command 
# ---------------------------------------
# remote login -> take login, execute command and comeout or login inside the server and execute the command.
# when we dont have readymade modules avilable, we can execute command or shell module 
# command module -> a simple command no need of access to shell environment like variables,bash,piping,etc ...
# shell module -> can access variabless,pipes,redirections,shell,environment,etc.

